"""add image url col to tags

Revision ID: c5e6eac884b8
Revises: f5815b3ce191
Create Date: 2020-09-08 22:21:14.246416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e6eac884b8'
down_revision = 'f5815b3ce191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'image_url')
    # ### end Alembic commands ###
