"""initial migration

Revision ID: c757c0474c01
Revises: 
Create Date: 2020-09-06 22:15:13.025709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c757c0474c01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_token', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'user', ['avatar_url'])
    op.create_unique_constraint(None, 'user', ['auth_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'location')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'auth_token')
    # ### end Alembic commands ###
